const imgPath = `../assets/images/`;
const iconPath = `../assets/icons/`;

export const images = {
  authBackground: require(`${imgPath}BG.png`),
  mainLogo: require(`${imgPath}mainLogo.png`),
  onBoardingBackGround: require(`${imgPath}onBoardingBackGround.png`),
  onBoarding1: require(`${imgPath}onBoarding1.png`),
  onBoarding2: require(`${imgPath}onBoarding2.png`),
  onBoarding3: require(`${imgPath}onBoarding3.png`),
  selectLanguage: require(`${imgPath}selectLanguage.png`),
  locationPermision: require(`${imgPath}locationPermision.png`),
  carasolu: require(`${imgPath}carasolu.png`),
  popularOne: require(`${imgPath}popularOne.png`),
  populartwo: require(`${imgPath}populartwo.png`),
  popularThree: require(`${imgPath}popularThree.png`),
  popularFour: require(`${imgPath}popularFour.png`),
  item1: require(`${imgPath}item1.png`),
  item2: require(`${imgPath}item2.png`),
  item3: require(`${imgPath}item3.png`),
  item4: require(`${imgPath}item4.png`),
  item5: require(`${imgPath}item5.png`),
  item6: require(`${imgPath}item6.png`),
  LogoOnly: require(`${imgPath}LogoOnly.png`),
  userProfile: require(`${imgPath}userProfile.png`),
};

export const icons = {
  account: require(`${iconPath}account.png`),
  email: require(`${iconPath}email.png`),
  password: require(`${iconPath}password.png`),
  checkedCheckBox: require(`${iconPath}checkedCheckBox.png`),
  bookH: require(`${iconPath}bookH.png`),
  foodH: require(`${iconPath}foodH.png`),
  electronicsH: require(`${iconPath}electronicsH.png`),
  computerH: require(`${iconPath}computerH.png`),
  cellPhone: require(`${iconPath}cellPhone.png`),
  office: require(`${iconPath}office.png`),
  shoesH: require(`${iconPath}shoesH.png`),
  fashionsH: require(`${iconPath}fashionsH.png`),
  collectionH: require(`${iconPath}collectionH.png`),
  menu: require(`${iconPath}menu.png`),
  cart: require(`${iconPath}cart.png`),
  backArrow: require(`${iconPath}backArrow.png`),
  PlusIcon: require(`${iconPath}PlusIcon.png`),
  MinusIcon: require(`${iconPath}MinusIcon.png`),
  home: require(`${iconPath}home.png`),
  categories: require(`${iconPath}categories.png`),
  orders: require(`${iconPath}orders.png`),
  heart: require(`${iconPath}heart.png`),
  settings: require(`${iconPath}settings.png`),
  notification: require(`${iconPath}notification.png`),
  FAQ: require(`${iconPath}FAQ.png`),
  star: require(`${iconPath}emptyStar.png`),
};
